JEIEvents.information(e => {
//End Remastered
  e.addItem('endrem:black_eye', ['Found in the Pirate Village, Buried Treasure, and Shipwrecks.']),
  e.addItem('endrem:cold_eye', ['Dropped by the Frostmaw.']),
  e.addItem('endrem:corrupted_eye', ['Found in Pillager Fortresses.']),
  e.addItem('endrem:lost_eye', ['Obtained through Bounty Board Quests with a Reputation of 15 or greater.']),
  e.addItem('endrem:nether_eye', ['Found in the Nether Fortress.']),
  e.addItem('endrem:old_eye', ['Found in the Desert Labyrinth or dropped by the largest of Deathworms.']),
  e.addItem('endrem:rogue_eye', ['Found in the Tinkers Workshop.']),
  e.addItem('endrem:cursed_eye', ['Found in Bastions or rarely obtained through Piglin Bartering.']),
  e.addItem('endrem:evil_eye', ['Traded from a Master level Cleric.']),
  e.addItem('endrem:guardian_eye', ['Crafted from Elder Guardian Eyes.']),
  e.addItem('endrem:magical_eye', ['Created through combining magical essences in an Enchanting Apparatus.']),
  e.addItem('endrem:wither_eye', ['Dropped by the Wither.']),
  e.addItem('endrem:witch_eye', ['Obtained through Witch Haggling.']),
  e.addItem('endrem:undead_eye', ['Obtained through combining multiple undead essences in a Cooking Pot.']),
  e.addItem('endrem:exotic_eye', ['Obtained through combining many exotic materials.']),
  e.addItem('endrem:cryptic_eye', ['Very rarely obtained through FTB Quest rewards.']),

//Alexs Caves General
  e.addItem('alexscaves:cave_tablet', ['Decode on a Spelunkery Table.']),
  e.addItem('alexscaves:cave_codex', ['Use to unlock new chapters on the Cave Codex or combine with a Map to obtain a Cave Biome Map.']),

//Alexs Caves Magnetic Caves
  e.addItem('minecraft:iron_boots', ['Walk on any surface of a Scarlet Neodymium block with these']),
  e.addItem('alexscaves:scarlet_neodymium_node', ['Walk on with iron boots.']),
  e.addItem('alexscaves:scarlet_neodymium_pillar', ['Walk on with iron boots.']),
  e.addItem('alexscaves:block_of_scarlet_neodymium', ['Walk on with iron boots.']),
  e.addItem('alexscaves:seeking_arrow', ['Curves towards the nearest entity.']),
  e.addItem('alexscaves:magnetic_levitation_rail', ['Lifts Minecarts off the rail.']),
  e.addItem('alexscaves:azure_magnet', ['Pulls up to 27 connected metallic blocks. Increase range with Azure Neodymium Ingots and decrease with Scarlet Neodymium Ingots.']),
  e.addItem('alexscaves:scarlet_magnet', ['Pushs up to 27 connected metallic blocks. Increase range with Scarlet Neodymium Ingots and decrease with Azure Neodymium Ingots.']),
  e.addItem('alexscaves:holocoder', ['Right click to bind to an entity. When placed into a Hologram Projector, displays bound entity or displays yourself if left unbound.']),
  e.addItem('alexscaves:quarry_smasher', ['Set a field with four Magnetic Lights with a Magnetic Quarry one block outside between 2 of the Magnetic Lights (in the center). Place a Quarry Smasher within these bounds to activate. Will mine out any blocks underneath its designated area and the drops will be sent to the top of the Magnetic Quarry.']),
  e.addItem('alexscaves:magnetic_light', ['Set a field with four Magnetic Lights with a Magnetic Quarry one block outside between 2 of the Magnetic Lights (in the center). Place a Quarry Smasher within these bounds to activate. Will mine out any blocks underneath its designated area and the drops will be sent to the top of the Magnetic Quarry.']),
  e.addItem('alexscaves:quarry', ['Set a field with four Magnetic Lights with a Magnetic Quarry one block outside between 2 of the Magnetic Lights (in the center). Place a Quarry Smasher within these bounds to activate. Will mine out any blocks underneath its designated area and the drops will be sent to the top of the Magnetic Quarry.']),
  e.addItem('alexscaves:tesla_bulb', ['Zaps anything that walks nearby. Explodes if broken or hit with a projectile.']),
  e.addItem('alexscaves:galena_gauntlet', ['Use with a metal tool (including Netherite) in offhand. When used, launches tool or weapon 20 blocks in any direction.']),
  e.addItem('alexscaves:resistor_shield', ['Switch polarities with Shift Right Click. Azure repels enemies, Scarlet pulls enemies closer.']),
  e.addItem('alexscaves:heart_of_iron', ['Dropped when a Magnetron is killed.']),
  e.addItem('alexscaves:scrap_metal', ['Converted to the rusty version when acid runs over it.']),
  e.addItem('alexscaves:scrap_metal_plate', ['Converted to the rusty version when acid runs over it.']),
  e.addItem('alexscaves:metal_rebar', ['Converted to the rusty version when acid runs over it.']),
  e.addItem('alexscaves:metal_scaffolding', ['Converted to the rusty version when acid runs over it.']),
  e.addItem('alexscaves:metal_barrel', ['Converted to the rusty version when acid runs over it.']),

//Alexs Caves Primordial Cave
  e.addItem('alexscaves:limestone_spear', ['Deals low ranged and melee damage.']),
  e.addItem('alexscaves:smooth_limestone', ['Apply Charcoal to Smooth Ancient Limestone to create Cave Paintings.']),
  e.addItem('minecraft:charcoal', ['Apply Charcoal to Smooth Ancient Limestone to create Cave Paintings.']),
  e.addItem('alexscaves:pine_nuts', ['Produced by Pewen trees.']),
  e.addItem('alexscaves:tree_star', ['Produced by Ancient Jungle trees.']),
  e.addItem('alexscaves:spawn_egg_subterranodon', ['Lured and bred with Cod. Tamed with Trilocaris Tails. Interact with while sneaking to command to Stay, Follow, or Wander. Interact with normally to ride.']),
  e.addItem('alexscaves:spawn_egg_vallumraptor', ['Packs are led by an Elder (denoted by orange markings) and disperse if the Elder is killed. Can open doors and chests to steal any meats. If a Dinosaur Nugget is taken itll enter a relaxed state in which it can be fed a Serene Salad to tame. Breed tamed Vallumraptors with Dinosaur Nuggets. Babies will imprint on their parents owners.']),
  e.addItem('alexscaves:spawn_egg_grottoceratops', ['Produce Fiddleheads which appear after they pick up and eat a Curly Fern. Bred with Tree Stars.']),
  e.addItem('alexscaves:spawn_egg_trilocaris', ['Bucketable.']),
  e.addItem('alexscaves:spawn_egg_tremorsaurus', ['Tame by hitting with a Primitive Club to stun, then by feeding Serene Salad afterwards. Takes several attempts. Can be ridden and made to roar (scares away all nearby mobs). Breed once tamed with Dinosaur Chops. Babies will imprint on their parents owners.']),
  e.addItem('alexscaves:spawn_egg_relicheirus', ['Feed a Relicheirus some Primordial Soup to energize them and cause them to knock down any nearby trees. Breed Relicheirus with Tree Stars.']),
  e.addItem('alexscaves:primordial_soup', ['Feed a Relicheirus some Primordial Soup to energize them and cause them to knock down any nearby trees. Breed Relicheirus with Tree Stars.']),
  e.addItem('alexscaves:amber_monolith', ['Repopulates the nearby area depending on the natural spawn rates.']),
  e.addItem('alexscaves:serene_salad', ['Removes the Stunned effect when consumed. Used to tame Tremorsaurus and Vallumraptors.']),
  e.addItem('alexscaves:seething_stew', ['Grants Rage, which boost damage based on how little health is left.']),
  e.addItem('alexscaves:primitive_club', ['Inflicts Stunned on targets. Renders them unable to move or melee attack.']),
  e.addItem('alexscaves:primordial_helmet', ['When equipped, increases the health and saturation provided by consuming raw meat per each piece.']),
  e.addItem('alexscaves:primordial_tunic', ['When equipped, increases the health and saturation provided by consuming raw meat per each piece.']),
  e.addItem('alexscaves:primordial_pants', ['When equipped, increases the health and saturation provided by consuming raw meat per each piece.']),
  e.addItem('alexscaves:ominous_catalyst', ['Throw into a volcano to summon the Luxtructosaurus.']),
  e.addItem('alexscaves:tectonic_shard', ['Use on inhabitants of the Primordial Caves to change their skin into an Eruption style.']),
  e.addItem('alexscaves:amber_curiosity', ['Rarely drops from mining Amber. Use on inhabitants of the Primordial Caves to change their skin into a Retro style.']),
  e.addItem('alexscaves:ambersol', ['Shines light downwards without limit.']),

//Alexs Caves Toxic Caves
  e.addItem('alexscaves:spawn_egg_nucleeper', ['Causes a Nuclear Explosion.']),  
  e.addItem('alexscaves:spawn_egg_radgill', ['Bucketable with Acid.']),  
  e.addItem('alexscaves:spawn_egg_gammaroach', ['Attacks anything that is Irradiated.']),  
  e.addItem('alexscaves:spawn_egg_raycat', ['Tamed and bred with Radgills. Scares off Nucleepers and occasionally absorbs the Irradiated effect from their owner. Heals whenever absorbing Irradiated from nearby creatures.']),  
  e.addItem('alexscaves:acid_bucket', ['Convert scrap metal to the rusty version when acid runs over it. Rapidly corrodes armor when stood in. Produces mud when interacting with Water, Cobblestone when interacting with non-source blocks of Lava, and Radrock if Lava interacts with the source block of Acid.']),
  e.addItem('alexscaves:unrefined_waste', ['Applies the Irradiated effect when walked over.']),
  e.addItem('alexscaves:block_of_uranium', ['Applies the Irradiated effect when held.']),
  e.addItem('alexscaves:uranium', ['Applies the Irradiated effect when held.']),
  e.addItem('alexscaves:uranium_shard', ['Applies the Irradiated effect when held.']),
  e.addItem('alexscaves:uranium_rod', ['Applies the Irradiated effect when held.']),
  e.addItem('alexscaves:waste_drum', ['Applies the Irradiated effect when held. Creates a small explosion if disposed of in fire or lava.']),
  e.addItem('alexscaves:charred_remnant', ['Applies the Irradiated effect when held.']),
  e.addItem('alexscaves:radrock_uranium_ore', ['Applies the Irradiated effect when held.']),
  e.addItem('alexscaves:sulfur', ['Grows the Sulfur Buds if an Acidic Radrock is placed above it.']),
  e.addItem('alexscaves:sulfur_bud_small', ['Drops Sulfur. Grows the Sulfur Buds if an Acidic Radrock is placed above it.']),
  e.addItem('alexscaves:sulfur_bud_medium', ['Drops Sulfur. Grows the Sulfur Buds if an Acidic Radrock is placed above it.']),
  e.addItem('alexscaves:sulfur_bud_large', ['Drops Sulfur. Grows the Sulfur Buds if an Acidic Radrock is placed above it.']),
  e.addItem('alexscaves:sulfur_cluster', ['Drops Sulfur. Grows the Sulfur Buds if an Acidic Radrock is placed above it.']),
  e.addItem('alexscaves:acidic_radrock', ['Grows the Sulfur Buds if placed above it.']),
  e.addItem('spelunkery:sulfur', ['Drops Sulfur. Grows the Sulfur Buds if an Acidic Radrock is placed above it.']),
  e.addItem('alexscaves:radon_bottle', ['Obtained by using an empty bottle on a Geothermal Vent above an Acid source block.']),
  e.addItem('alexscaves:disc_fragment_fusion', ['Obtained when a Tremorzilla kills a Nucleeper with a Nuclear Laser.']),
  e.addItem('alexscaves:tremorzilla_egg', ['Hatch by setting off a Nuclear Explosion within 72 blocks of where the Egg is placed.']),
  e.addItem('alexscaves:spelunkie', ['Allows healing even if Irradiated.']),
  e.addItem('alexscaves:slam', ['Allows healing even if Irradiated.']),
  e.addItem('alexscaves:green_soylent', ['Allows healing even if Irradiated.']),
  e.addItem('alexscaves:nuclear_bomb', ['Causes a massive explosion that affects all nearby mobs with Irradiation. Will hatch a Tremorzilla egg if is within 72 blocks of the explosion and triggers Nuclear Sirens in 255 blocks. Defuse with Shears.']),
  e.addItem('alexscaves:nuclear_siren', ['Emits noise if a Nucleeper, Nuclear Bomb, or a Nuclear Furnace is going to explode or a Tremorzilla is going to fire its nuclear beam within 255 blocks.']),
  e.addItem('alexscaves:hazmat_mask', ['Lowers the damage and effects of Irradiation and Acid.']),
  e.addItem('alexscaves:hazmat_chestplate', ['Lowers the damage and effects of Irradiation and Acid.']),
  e.addItem('alexscaves:hazmat_leggings', ['Lowers the damage and effects of Irradiation and Acid.']),
  e.addItem('alexscaves:hazmat_boots', ['Lowers the damage and effects of Irradiation and Acid.']),
  e.addItem('alexscaves:remote_detonator', ['Allows remote trigger of registered explosives.']),
  e.addItem('alexscaves:raygun', ['Inflicted Irradiation. Requires Uranium Rods as fuel.']),
  e.addItem('alexscaves:nuclear_furnace_component', ['Create a Nuclear Furnace by placing 8 Nuclear Furnace Component blocks together. Similar to, but 5x faster than a Blast Furnace. Uses Uranium Rods as fuel, but produces Unrefined Waste as a byproduct. To prevent it from exploding, Metal Barrels need to be provided to store the Unrefined Waste.']),

//Alexs Caves Abyssal Caves
  e.addItem('alexscaves:spawn_egg_sea_pig', ['Sifts through Muck to look for anything edible. Feed Muck, Clay Balls, or Mud to cause Sea Pigs to produce Muck, Clay, Bone Meal, Sea Glass Shards, Pearls, and Marine Snow. Bucketable.']), 
  e.addItem('alexscaves:spawn_egg_hullbreaker', ['Will investigate and eventually attacks anything that emits light or glows.']), 
  e.addItem('alexscaves:spawn_egg_gossamer_worm', ['Bucketable. Favorite prey of Hullbreakers.']), 
  e.addItem('alexscaves:spawn_egg_tripodfish', ['Bucketable. Found near the sea floor.']), 
  e.addItem('alexscaves:spawn_egg_lanternfish', ['Bucketable. May be found near the ocean surface near Abyssal Chasms.']), 
  e.addItem('alexscaves:spawn_egg_deep_one', ['Is initially wary of intruders. Attacking and damaging Deep Ones damages your Reputation and if low enough, will cause you to attacked on sight. Improve Reputation by offering them Pearls or Hearts of the Sea on Abyssal Altars to barter.']), 
  e.addItem('alexscaves:spawn_egg_deep_one_knight', ['Is initially wary of intruders. Attacking and damaging Deep Ones damages your Reputation and if low enough, will cause you to attacked on sight. Improve Reputation by offering them Pearls or Hearts of the Sea on Abyssal Altars to barter.']), 
  e.addItem('alexscaves:spawn_egg_deep_one_mage', ['Is initially wary of intruders. Attacking and damaging Deep Ones damages your Reputation and if low enough, will cause you to attacked on sight. Improve Reputation by offering them Pearls or Hearts of the Sea on Abyssal Altars to barter.']), 
  e.addItem('alexscaves:mussel', ['Spreads to nearby blocks, esp. Wood. When broken, may drop Pearls.']),   
  e.addItem('alexscaves:pearl', ['May be dropped when breaking Mussels. Offer on an Abyssal Altar to appease the Deep Ones.']), 
  e.addItem('alexscaves:depth_glass', ['Allows clearer vision through Water.']),   
  e.addItem('alexscaves:gazing_pearl', ['Changes color based on the Deep Ones modd towards outsiders. Obtained through Deep One Bartering (offer Pearls or Hearts of the Sea on an Abyssal Altar).']),  
  e.addItem('alexscaves:sea_glass_shards', ['Rarely dropped by breaking Muck, higher chance with Fortune. Obtained through Deep One Bartering or through feeding Sea Pigs Muck, Mud, or Clay Balls.']),   
  e.addItem('alexscaves:marine_snow', ['Use on Dead Coral to bring them back to life. Can also grow Sponges and other kinds of sea life. May be dropped by Sea Pigs when fed Mud, Muck, or Clay Balls.']),   
  e.addItem('alexscaves:ortholance', ['Hold down Right-click to charge a charge attack that leaves waves in its wake. May be obtained through Deep One Knight Bartering (offering Pearls or Hearts of the Sea on an Abysssal Altar).']),   
  e.addItem('alexscaves:magic_conch', ['Use to summon multiple Deep Ones to aid you in combat. Only stick around for a short period. May be obtained through Deep One Knight Bartering (offering Pearls or Hearts of the Sea on an Abysssal Altar).']),   
  e.addItem('alexscaves:sea_staff', ['Right-click to send out water attacks that arc toward nearby mobs. May be obtained through Deep One Mage Bartering (offering Pearls or Hearts of the Sea on an Abysssal Altar).']),   
  e.addItem('alexscaves:depth_charge', ['Can be thrown. Creates an explosion that destroys blocks, even under water.']),   
  e.addItem('alexscaves:floater', ['When used, quickly returns you to the water surface.']),   
  e.addItem('alexscaves:bioluminescent_torch', ['Produces light underwater.']),   
  e.addItem('alexscaves:diving_helmet', ['Grants 40 seconds of Water Breathing.']), 
  e.addItem('alexscaves:diving_leggings', ['Grants faster swimming speed.']),   
  e.addItem('alexscaves:diving_boots', ['Grants faster walking speed on Muck.']),   
  e.addItem('alexscaves:drain', ['Moves fluids from an upward space downwards, as long as there is space for them.']),   
  e.addItem('alexscaves:submarine', ['Creating a Submarine by surrounding an Enigmatic Engine with 20 Copper Blocks and 6 Depth Glass to mark the front. Repaired the Submarine with Copper Ingots and remove oxidation with an Axe.']),   
  e.addItem('alexscaves:enigmatic_engine', ['Creating a Submarine by surrounding an Enigmatic Engine with 20 Copper Blocks and 6 Depth Glass to mark the front. Repaired the Submarine with Copper Ingots and remove oxidation with an Axe.']),   

//Alexs Caves Forlorn Hollow
  e.addItem('alexscaves:spawn_egg_gloomoth', ['Passive. Attracted to light. When used as a sacrifice during a Underzealot Ritual, results in a Watcher.']), 
  e.addItem('alexscaves:spawn_egg_underzealot', ['Breaks light sources. Performs Rituals, sacrificing certain mobs to spawn others.']), 
  e.addItem('alexscaves:spawn_egg_watcher', ['Possesses the creature its attacking, preventing them from moving and forcing them to view the world through their view. Spawns when Underzealots sacrifice Gloomoths during their Rituals.']), 
  e.addItem('alexscaves:spawn_egg_corrodent', ['Flees from light.']), 
  e.addItem('alexscaves:spawn_egg_vesper', ['Blocking their attacks with a Shield temporarily ground them. When sacrificed during an Underzealot Ritual, spawns a Forsaken, a very powerful monster.']), 
  e.addItem('alexscaves:spawn_egg_forsaken', ['Heals as long as it is not in direct light. Spawned when Underzealots sacrifice Vespers during their Rituals.']), 
  e.addItem('alexscaves:fertilizer', ['Works like a stronger bonemeal.']), 
  e.addItem('alexscaves:moth_dust', ['Can be thrown and will cause any mob hit to be moth scented, making it a target for attack by any Forlorn Hollows creatures.']), 
  e.addItem('alexscaves:moth_ball', ['Can be placed. Keeps Gloomoths away from light sources.']), 
  e.addItem('alexscaves:desolate_dagger', ['Has a delayed second hit.']), 
  e.addItem('alexscaves:totem_of_possession', ['Bind to a target by hitting them. Right click to control where the bound creature goes and what it will attack. The possessed target needs to remain in sight.']), 
  e.addItem('alexscaves:beholder', ['Bind an Occult Gem. Use the Occult Gem to view through the Beholder.']), 
  e.addItem('alexscaves:burrowing_arrow', ['Pierces its targets and breaks up to 5 blocks.']), 
  e.addItem('alexscaves:dreadbow', ['Loads arrows more slowly, but when used, sends a volley of shadowy arrows.']), 
  e.addItem('alexscaves:hood_of_darkness', ['The Hood and Cloak of Darkness builds up Darkness overtime while worn. When the meter is full, press "G" to enter Shadow Mode, granting extremely fast flight for 10 seconds. Extend the length with a Darkened Apple']), 
  e.addItem('alexscaves:cloak_of_darkness', ['The Hood and Cloak of Darkness builds up Darkness overtime while worn. When the meter is full, press "G" to enter Shadow Mode, granting extremely fast flight for 10 seconds. Extend the length with a Darkened Apple']), 
  e.addItem('alexscaves:darkened_apple', ['The Hood and Cloak of Darkness builds up Darkness overtime while worn. When the meter is full, press "G" to enter Shadow Mode, granting extremely fast flight for 10 seconds. Extend the length with a Darkened Apple']), 
  e.addItem('alexscaves:guano', ['Can be thrown.']), 

//Alexs Mobs Mob JEI Info
  e.addItem('alexsmobs:spawn_egg_grizzly_bear', ['Will become hostile upon being approached, unless recently sated with honey. Tamed by feeding it salmon when sated with honey.']),
  e.addItem('alexsmobs:spawn_egg_crocodile', ['Hostile, but can be bred with rotten flesh.', 'Crocodiles growing up around a player will defend its area of birth from monsters.']),
  e.addItem('alexsmobs:spawn_egg_fly', ['Bred with rotten flesh.']),
  e.addItem('alexsmobs:spawn_egg_hummingbird', ['Bred with flowers and pollinates nearby flowers. Can be kept in an area with a hummingbird feeder.']),
  e.addItem('alexsmobs:spawn_egg_orca', ['Swimming with them grants the Orcas Might effect.']),
  e.addItem('alexsmobs:spawn_egg_sunbird', ['Orbits any beacon it can find and sets nearby undead mobs on fire.', 'Grants Sunbirds Blessing when flying nearby and Sunbirds Curse if attacked.']),
  e.addItem('alexsmobs:spawn_egg_gorilla', ['Become friendly if given Bananas, obtained by breaking Jungle Leaves.']),
  e.addItem('alexsmobs:spawn_egg_endergrade', ['Can be saddled and rid. Control with Chorus Fruit on a Stick']),
  e.addItem('alexsmobs:spawn_egg_hammerhead_shark', ['Targets fish, squids, and any mobs below half health. May drop Shark Teeth upon attacking prey.']),
  e.addItem('alexsmobs:spawn_egg_komodo_dragon', ['Tamed with stacks of Rotten Flesh and can be saddled.', 'Occasionally drops Komodo Dragon Spit.']),  
  e.addItem('alexsmobs:spawn_egg_capuchin_monkey', ['Tamed with Bananas, obtained by breaking Jungle Leaves.', 'Can ride the owners shoulder. Feed Eggs to heal, bred with Maggots, give Cobblestone or Ancient Darts to let them use their ranged attack.']),
  e.addItem('alexsmobs:spawn_egg_warped_toad', ['Tamed and bred with Crimson Mosquito Larva. Healed with Maggots.']),
  e.addItem('alexsmobs:spawn_egg_moose', ['Chance to drop their Antlers every 7-10 days. Takes 3-5 days to regrow. Bred with dandelions.']),
  e.addItem('alexsmobs:spawn_egg_raccoon', ['Steals food out of chests.', 'Tamed if given a Chicken Egg near water to wash and bred with Bread. Give a Carpet to give them a bandana and remove with shears.', 'Rarely steals items from Villager inventories.']),
  e.addItem('alexsmobs:spawn_egg_blobfish', ['Can be given a Slimeball to allow them to survive on land']),
  e.addItem('alexsmobs:spawn_egg_seal', ['Bred with Lobster Tails. Feed 3 Fish to a basking seal to initiate a trade.']),
  e.addItem('alexsmobs:spawn_egg_cockroach', ['Bred with Sugar.']),
  e.addItem('alexsmobs:spawn_egg_shoebill', ['Fishes when left alone. Feed Crocodile Eggs to increase the "lure" effect and Terrapin Eggs to increase the "luck" effect.']),
  e.addItem('alexsmobs:spawn_egg_elephant', ['Tame calfs and non-tusked Elephants with Acacia Blossoms and breed tamed Elephants with Acacia Blossoms.', 'Can be ridden, given Chests, and given Carpets. Remove with Shears.', 'Tamed Tusked Elephants can be made to charge by feeding Wheat.']),
  e.addItem('alexsmobs:spawn_egg_snow_leopard', ['Bred with Moose Ribs. Hunts prey mobs and when successful, more items are dropped, as if killed with a high level of Looting.']),
  e.addItem('alexsmobs:spawn_egg_spectre', ['Lure with Soul Hearts. Can use a Lead to take a trip across the End with it.']),
  e.addItem('alexsmobs:spawn_egg_crow', ['Damages crops, but can be scared away with a Carved Pumpkin. Tame by dropping Pumpkin Seeds for them to eat. Tamed crows will sit on Hay Blocks to regain health and can fly around the Hay Block to gather items. Will play items in containers with the same Item Frame. Deals extra damage to undead mobs.']),
  e.addItem('alexsmobs:spawn_egg_alligator_snapping_turtle', ['Moss grows overtime. Shear when mossy for a chance of getting Spiked Scute.']),
  e.addItem('alexsmobs:spawn_egg_mungus', ['Feed mushrooms they have to grow more. If slain with 5 or more mushrooms, they explode and convert the neighboring land into mushroom biome of the relative type. With more than 1 mushroom, they will fire beams at mushrooms of the same type to grow more or grow a mushroom over mycelium into giant mushrooms.']),
  e.addItem('alexsmobs:spawn_egg_mantis_shrimp', ['Tame with Tropical Fish, breed with Lobster Tails, heal with fish. Can be given a block by shift-right clicking and will seek out blocks of the same type to break.']),
  e.addItem('alexsmobs:spawn_egg_warped_mosco', ['Spawns when a Crimson Mosquito feeds on a Mungus with Warped Fungi.']),
  e.addItem('alexsmobs:spawn_egg_straddler', ['Become friendly if given Bananas, obtained by breaking Jungle Leaves.']),
  e.addItem('alexsmobs:spawn_egg_stradpole', ['Can be bucketted. Survives in water or lava. Feed a Crimson Mosquito Larva to cause them to grow into an adult.']),
  e.addItem('alexsmobs:spawn_egg_emu', ['Bred with Wheat. Good at dodging arrows, and Emu Feathers can be used to make leggings that grant a chance to avoid projectile damage.']),
  e.addItem('alexsmobs:spawn_egg_platypus', ['Bred with Lobster Tails. Can be bucketed. Tempted with Redstone and can be fed Redstone to make them dig through Clay to find Clay Balls and Maggots. Feeding Redstone Blocks increases the number of items dug up.']),  
  e.addItem('alexsmobs:spawn_egg_tasmanian_devil', ['Fed Rotten Flesh to cause them to howl and scare away hostile mobs. Breed with meat.']),
  e.addItem('alexsmobs:spawn_egg_kangaroo', ['Tame with Carrots and bred with Grass. Shift-right click to access their inventory. Can be give swords, armor, and any non-meat food, used to heal themselves.']),
  e.addItem('alexsmobs:spawn_egg_cachalot_whale', ['Hunts Squid and may drop teeth in the process. May be beached during Thunderstorms and if pushed back in, rewards savior with Ambergris.']),
  e.addItem('alexsmobs:spawn_egg_leafcutter_ant', ['Harvests leaves with a chance to create a new Anthill every 5 leaves, if a queen is still present. Stomp on the hive to find the Queen. Pacify with Gongylidia.']),
  e.addItem('alexsmobs:spawn_egg_enderiophage', ['Created by placing an Eye of Ender into a Capsid placed above an End Rod. Afflicts Ender Flu, which can be removed by Milk or Chorus Fruit. Hostile to Enderman and Endergrades. When Ender Flus timer runs out, many smaller Enderiophages burst out and the victim takes heavy damage.']),
  e.addItem('alexsmobs:spawn_egg_bald_eagle', ['Lured and tamed with Fish Oil. Heal with Fish, tame with Rotten Flesh. Pick up with Falconry Gloves and punch to launch at enemies. Can be used for scouting if given a Falconry Hood.']),
  e.addItem('alexsmobs:spawn_egg_tiger', ['Grarnts Tigers Blessing if fed Chicken or Porkchops. Lets you approach Tigers without being attacked. Tigers will also aid you if you are attacked. Bred with Acacia Blossoms.']),
  e.addItem('alexsmobs:spawn_egg_tarantula_hawk', ['Tame with Spider Eyes, bred with Fermented Spider Eyes (needs nearby Spiders to paralyze), heal with Flowers.']),
  e.addItem('alexsmobs:spawn_egg_void_worm', ['Baited by tossing a Mysterious Worm into the Ends Void.']),
  e.addItem('alexsmobs:spawn_egg_frilled_shark', ['Afflicts Exsanguination (quickly drains health). May drop its teeth upon attacking Squid.']),
  e.addItem('alexsmobs:spawn_egg_mimic_octopus', ['Tamed with Lobster Tails if not camouflaged, bred with Tropical Fish. Attacked by Mantis Shrimp and Sharks. If on land, give Slimeballs every few days to avoid drying out. Give an Ink Sac to cause it to change form. Give it Prismarine to make it mimic a Guardian or a Pufferfish to mimic a Pufferfish or Gunpowder to mimic a Creeper. Give 5-8 Mimicream to let them use the abilities of what they mimic.']),
  e.addItem('alexsmobs:spawn_egg_seagull', ['Bred with Cod. Steals food every one to three minutes. If holding a Buried Treasure Map and have tossed a Lobster tail onto the ground, the Seagull that eats it will sit directly above the buried treasure.']),
  e.addItem('alexsmobs:spawn_egg_froststalker', ['Bred with Porkchops while wearing a Froststalker Helmet.']),
  e.addItem('alexsmobs:spawn_egg_tusklin', ['Can be saddled and ridden for a short time before being bucked off. Can be equiped with Ancient Hogshoes. Pacify with Brown Mushrooms, breed with Red Mushrooms. Young Tusklins can dig up Brown Mushrooms from the dirt.']),
  e.addItem('alexsmobs:spawn_egg_laviathan', ['Laviathans can be ridden with Straddlite Saddle and controlled with Straddlite Tack. Allows up to four passengers. Solidifies into a stronger Obsidian form when in water. Breed with Crimson Mosquito Larva and healed with Magma Cream.']),
  e.addItem('alexsmobs:spawn_egg_cosmaw', ['Tamed and bred with Cosmic Cod, healed with Chorus Fruit. Will save owners who fall off the edge of an End island']),
  e.addItem('alexsmobs:spawn_egg_toucan', ['Bred with Eggs. Feed an Apple for a chance to place an Oak Sapling, feed a Banana for a chance to plant a Jungle Sapling. Feed a Golden Apple to make them plant saplings at a faster rate. Feed an Enchanted Golden Apple to let Toucans plant saplings without need to be fed fruit.']),
  e.addItem('alexsmobs:spawn_egg_maned_wolf', ['Bred with the meat of Rabbits or Chicken. When fed Apples, releases a smell that attracts other animals to the area and increases the production of fungus in nearby Leafcutter Anthills.']),
  e.addItem('alexsmobs:spawn_egg_anaconda', ['Preys on anything small enough. After several large meals, sheds it skin. Pacified and bred with Chicken.']),
  e.addItem('alexsmobs:spawn_egg_anteater', ['Preys on Leafcutter Ants. When attacking an anthill, may undercover dirt, rooted dirt, pupae, tubers, fungus, and other items. Bred with Leafcutter Ant Pupae.']),
  e.addItem('alexsmobs:spawn_egg_flutter', ['Bucketable (flowerpot while sneaking if tamed). Tamed with 4-6 flowers that are different than each other. Can be equipped with a flower pot to give them armor. When near azalea bushes or leaves, chance for them to bloom. Healed with flowers, bred with bonemeal.']),
  e.addItem('alexsmobs:spawn_egg_gelada_monkey', ['Feed wheat to entice them to destroy most grass in an area. Bred with dead bushes.']),
  e.addItem('alexsmobs:spawn_egg_jerboa', ['Found only in desert biomes at night. Hunted by rattlesnakes, foxes, and cats. Begs for seeds and if give, grants Fleet-Footed (speed boost when running and jumping at the same time). Wont disappear if fed Seeds or Maggots. Bred with Maggots or small insects.']),
  e.addItem('alexsmobs:spawn_egg_terrapin', ['Bucketable. If jumped on, will recede into its shell. If jumped on again, will spin in the direction of the jumper. Bred with Sea Grass. Baby turtles may mutate to have a random color.']),
  e.addItem('alexsmobs:spawn_egg_comb_jelly', ['Bucketable.']),
  e.addItem('alexsmobs:spawn_egg_cosmic_cod', ['Bucketable (empty bucket). Damaged by water. If attacked, will attempt to teleport away. Prey of Cosmaws and used to tame them.']),
  e.addItem('alexsmobs:spawn_egg_bunfungus', ['Created by feeding a rabbit several Mungal spores, dropped by Mungi. Attacks any monster in their sight. Make completely passive (from neutral) by giving a carrot. Carrots also grants regeneration and strength.']),
  e.addItem('alexsmobs:spawn_egg_bison', ['Attack any person who comes to near. Shear to obtain Bison Fur. Sheared Bison need to eat plenty of grass to regain their shaggy coat. Adults clear any snow layers in their area. Bred with wheat. Remove snow in their coat with a shovel or add snow with snow.']),
  e.addItem('alexsmobs:spawn_egg_giant_squid', ['Hostile towards Guardians and Fish. If attacked by Cachalot Whales, may lose a Tentacles. Depressurized if under less than 10 blocks of water. When struck by lightning, may become a unique blue Giant Squid.']),
  e.addItem('alexsmobs:spawn_egg_devils_hole_pupfish', ['Only spawn in underground aquifers within a single chunk. Eats muck off submerged moss blocks and may dislodge slime balls. May reproduce with other pupfish after feeding on moss. Bucketable.']),
  e.addItem('alexsmobs:spawn_egg_catfish', ['Small and medium Catfish vacuum up any items they see. Small Catfish store up to three stacks of items, Medium Catfish can store up to nine. Large Catfish (only found in Swamps) may swallow any mob shorter than a block. Regurgitate any item or mob eaten if injured or if they encounter a Sea Pickle. Lured with Sea Lanterns. Bucketable.']),
  e.addItem('alexsmobs:small_catfish_bucket', ['Small and medium Catfish vacuum up any items they see. Small Catfish store up to three stacks of items, Medium Catfish can store up to nine. Large Catfish (only found in Swamps) may swallow any mob shorter than a block. Regurgitate any item or mob eaten if injured or if they encounter a Sea Pickle. Lured with Sea Lanterns. Bucketable.']),
  e.addItem('alexsmobs:medium_catfish_bucket', ['Small and medium Catfish vacuum up any items they see. Small Catfish store up to three stacks of items, Medium Catfish can store up to nine. Large Catfish (only found in Swamps) may swallow any mob shorter than a block. Regurgitate any item or mob eaten if injured or if they encounter a Sea Pickle. Lured with Sea Lanterns. Bucketable.']),
  e.addItem('alexsmobs:large_catfish_bucket', ['Small and medium Catfish vacuum up any items they see. Small Catfish store up to three stacks of items, Medium Catfish can store up to nine. Large Catfish (only found in Swamps) may swallow any mob shorter than a block. Regurgitate any item or mob eaten if injured or if they encounter a Sea Pickle. Lured with Sea Lanterns. Bucketable.']),
  e.addItem('alexsmobs:spawn_egg_flying_fish', ['Bucketable.']),
  e.addItem('alexsmobs:spawn_egg_rain_frog', ['Feed Maggots to breed. Will eat any small insect items they can find. Use a shovel on a burrowing frog to disturb it and prevent it from disappearing. May brings rain if pleased. Known to enjoy Music Discs.']),
  e.addItem('alexsmobs:spawn_egg_potoo', ['If in a location where it is dark enough for monsters to spawn, it will constantly shriek and its pupil will take up most of its eye. Handle and move with a Falconry Glove. Bred with Maggots.']),
  e.addItem('alexsmobs:spawn_egg_mudskipper', ['Tamed with Lobster Tails. Spits mud to defend its owner, inflicting slowness. Bred with Insect Larva or Lobster Tails.']),
  e.addItem('alexsmobs:spawn_egg_rhinoceros', ['Attacks anyone who gets too close. Will seek out and attack Pillagers on sight. Pacify with Wheat. If a potion is used on a Rhinoceros, it will be applied to its horn and any creature attacked will be inflicted with the potion effect. Lasts for 15-20 attacks. Befriended Rhinoceros aid anyone who has fed them wheat and will roam nearby villages for safety. Bred with Tall Grass or Dead Bushes.']),
  e.addItem('alexsmobs:spawn_egg_sugar_glider', ['Tamed with Sweet Berries. Place on ones head by sneak right-clicking and if on ones head, will grant Slow Falling. Tamed Sugar Gliders will forage through leaf blocks for items. Bred with Honeycombs.']),
  e.addItem('alexsmobs:spawn_egg_farseer', ['Found near the World Border. Attacks pierce through armor and enchantments.']),
  e.addItem('alexsmobs:spawn_egg_skreecher', ['Makes a loud noise when detecting intruders.']),
  e.addItem('alexsmobs:spawn_egg_underminer', ['Only damaged with Magic (ie. splash potions). Mines blocks which may have ore behind them. If dropped a specific ore block, will seek out similar ores in the surrounding area.']),
  e.addItem('alexsmobs:spawn_egg_skunk', ['If chased or damaged, will release a noxious spray, inflicting nausea. The spray lingers and can be bottled. If inflicted with a potion effect while spraying, will create a lingering cloud of the effect nearby. Bred with Sweet Berries.']),
  e.addItem('alexsmobs:spawn_egg_banana_slug', ['May drop some slime while moving around the world. Bred with Brown Mushrooms.']),
  e.addItem('alexsmobs:spawn_egg_blue_jay', ['Loves Glow Berries. If fed, will be charmed for a while, following the feeder through the world. If a Racoon is fed a Glow Berry during this time, they will be bonded and if the Racoon starts a fight, the Blue Jay will assist. Feed another Glow Berry to convince it to leave its friend. If fed a seed, will chirp a short song that reveals nearby monsters. Bred with Maggots or other insect larvae.']),
  e.addItem('alexsmobs:spawn_egg_caiman', ['Bred with Catfish and will lay eggs. When hatching, will imprint on the nearest entity. Will defend their owner by grabbing targets and holding them still.']),
  e.addItem('alexsmobs:spawn_egg_triops', ['Breed by tossing a carrot. Bucketable.']),

  //Alexs Mobs Item JEI Info
  e.addItem('alexsmobs:banana_peel', ['Obtained by giving Capuchin Monkeys Bananas. Can be placed on the ground.']),
  e.addItem('alexsmobs:banana', ['Obtained by breaking Jungle leaves.']),
  e.addItem('alexsmobs:fedora', ['Rarely obtained by granting Platypuses Redstone Blocks and allowing them to dig in Clay. Can be given to Playtpuses.']),
  e.addItem('alexsmobs:cachalot_whale_tooth', ['Obtained when Cachalot Whales attack Squid, Glow Squid, Mimic Octopuses, and Giant Squids.']),
  e.addItem('alexsmobs:shrimp_fried_rice', ['Obtained by giving a tamed Mantis Shrimp Rice, setting to Break Block mode, and then placing a Furnace or Smoker.']),
  e.addItem('alexsmobs:sombrero', ['Dropped by Cockroaches dancing to La Cucaracha.']),
  e.addItem('alexsmobs:crocodile_scute', ['Obtained when Baby Crocodiles grow into adults.']),
  e.addItem('alexsmobs:blood_sac', ['Dropped by Crimson Mosquitos which are inflated with blood.']),
  e.addItem('alexsmobs:blood_sprayer', ['Uses Blood Sacs as ammunition.']),
  e.addItem('alexsmobs:ancient_dart', ['Can be given to tamed Capuchin Monkeys to throw.']),
  e.addItem('alexsmobs:chorus_on_a_stick', ['Used to lead Endergrades.']),
  e.addItem('alexsmobs:mosquito_larva', ['Can be used to grow stradpoles into straddlers.']),
  e.addItem('alexsmobs:shark_tooth', ['May be dropped by Hammerhead Sharks preying on fish, squids, and mobs below half health.']),  
  e.addItem('alexsmobs:shark_tooth_arrow', ['Travels better underwater and deals more damage to aquatic creatures.']),  
  e.addItem('alexsmobs:komodo_spit', ['Occasionally dropped by Komodo Dragons.']),
  e.addItem('alexsmobs:moose_antler', ['May be dropped by Mooses every 7-10 days.']),
  e.addItem('alexsmobs:mimicream', ['Surround an Tool with 8 copies to make a copy with 0 durability. Apply 5-8 to a Mimic Octopus to allow them to use the abilities of what they mimic.']),
  e.addItem('alexsmobs:fish_oil', ['Grants Oiled. Lets you float in water and in rain.']),
  e.addItem('alexsmobs:maraca', ['Can be given to Cockroachs.']),
  e.addItem('alexsmobs:sombrero', ['Can be given to Cockroachs.']),
  e.addItem('alexsmobs:cockroach_ootheca', ['Produced by Cockroachs. Throw to hatch.']),
  e.addItem('alexsmobs:acacia_blossom', ['Rarely dropped by breaking Acacia Leaves. Obtained by Sugar Glider foraging on Acacia Leaves.']),
  e.addItem('alexsmobs:spiked_scute', ['May be dropped when shearing mossy snapping alligators.']),
  e.addItem('alexsmobs:pocket_sand', ['Uses Sand as ammo.']),
  e.addItem('alexsmobs:gustmaker', ['When activated with Redstone, sends a gust of wind that moves mobs and items,.']),
  e.addItem('alexsmobs:straddleboard', ['Dyable. Can be used to travel across lava, but may snap and throw you off.']),
  e.addItem('alexsmobs:ambergris', ['Gifted when saving beached Cachalot Whales. Smelts up to 64 items.']),
  e.addItem('alexsmobs:echolocator', ['Locates nearby caves.']),
  e.addItem('alexsmobs:endolocator', ['Locates the End Portal.']),
  e.addItem('alexsmobs:straddle_saddle', ['Laviathans can be ridden with Straddlite Saddle and controlled with Straddlite Tack. Allows up to four passengers. Solidifies into a stronger Obsidian form when in water. Breed with Crimson Mosquito Larva and healed with Magma Cream.']),
  e.addItem('alexsmobs:straddle_helmet', ['Laviathans can be ridden with Straddlite Saddle and controlled with Straddlite Tack. Allows up to four passengers. Solidifies into a stronger Obsidian form when in water. Breed with Crimson Mosquito Larva and healed with Magma Cream.']),
  e.addItem('alexsmobs:mungal_spores', ['Rarely shed by Mungi. Tempts Rabbits and when used on Rabbits, transforms them into Mungi. Used to breed Mungi.']),
  e.addItem('alexsmobs:squid_grapple', ['Acts as a grapple hook. Can shoot up to four tentacles. Sneak to detach.']),
  e.addItem('alexsmobs:lost_tentacle', ['Dropped by Giant Squid when slain by Cachalot Whales.']),
  e.addItem('alexsmobs:pupfish_locator', ['Locates chunks containing Devils Hole Pupfish.']),
  e.addItem('alexsmobs:novelty_hat', ['Rarely dropped by Skelewags.']),
  e.addItem('alexsmobs:leafcutter_ant_pupa', ['Obtained rarely by breaking Ant Chamber blocks. Use on dirt to create a new colony.']),
  e.addItem('alexsmobs:gongylidia', ['High saturation food. Obtained by interacting with chamber blocks, but upsets Ants unless shroomlight is present.']),
  e.addItem('alexsmobs:enderiophage_rocket', ['Can be used in place of Rockets for Elytra flying']),
  e.addItem('alexsmobs:capsid', ['Can store up to 64 of an item. Sends items upwards if there is another Capsid or Storage block above it.']),
  e.addItem('alexsmobs:falconry_glove', ['Used to pick up Bald Eagles and Potoos.']),
  e.addItem('alexsmobs:falconry_hood', ['Used to control Bald Eagles while they are flying.'])
  e.addItem('alexsmobs:mysterious_worm', ['It yearns for the Void of the End.']),
  e.addItem('alexsmobs:dimensional_carver', ['Tears open a portal back to your spawn.']),
  e.addItem('alexsmobs:shattered_dimensional_carver', ['Creates a portal that leads one million blocks in any direction.']),
  e.addItem('alexsmobs:serrated_shark_tooth', ['Dropped when Frilled Sharks attack Squid.']),
  e.addItem('alexsmobs:shield_of_the_deep', ['Afflicts attackers with Exsanguination (quickly drains health).']),
  e.addItem('alexsmobs:pigshoes', ['Obtained by Piglin Bartering. Enchantable. Equip to Tusklins.']),
  e.addItem('alexsmobs:shed_snake_skin', ['Shed by Anacondas after fed several large meals.']),
  e.addItem('alexsmobs:vine_lasso', ['Can lead hostile mobs but cant be attached to fence posts.']),
  e.addItem('alexsmobs:rainbow_jelly', ['Apply to mobs to grant a rainbow coloration. Eat to apply effect to yourself. Remove with a Sponge.']),
  e.addItem('alexsmobs:sculk_boomer', ['When activated with a Sculk Sensor, releases a loud sound pulse that damages nearby mobs. Disable with a redstone signal.']),
  e.addItem('alexsmobs:transmutation_table', ['Changes one item to one of three for an small EXP cost. Keeps a memory of previous transmutations and may offer them.']),
  e.addItem('alexsmobs:ghostly_pickaxe', ['Dropped by Underminers. Stores up to 9 stacks of blocks if your inventory is full. Upon a slot reopening, will populate that spot with a stored block.']),
  e.addItem('alexsmobs:tendon_whip', ['Reaches from over 8 blocks away and hits up to three nearby mobs.']),
  e.addItem('alexsmobs:unsettling_kimono', ['Increases the wearers placement abilities by 2 blocks and makes most undead monsters neutral.']),
  e.addItem('alexsmobs:stink_bottle', ['Obtained by using a Glass Bottle on lingering stink left by Skunks. Used as ammo in Stink Rays']),
  e.addItem('alexsmobs:stink_ray', ['Causes neutral and hostile mobs to attack anything sprayed with this. Passive mobs flee from any mob sprayed with this.']),
  e.addItem('alexsmobs:banana_slug_slime_block', ['Turns nearby water into Crystallized Banana Slug Mucus.']),
  e.addItem('alexsmobs:mosquito_repellent_stew', ['Grants the Mosquito Repellent effect, which causes Crimson Mosquitos to flee.']),
  e.addItem('alexsmobs:music_disc_thime', ['Obtained by Seal Trading.']),
  e.addItem('alexsmobs:hummingbird_feeder', ['Filled with either Water Bottles or Sugar. Attracts nearby Hummingbirds and improves their pollination effects.']),
  e.addItem('alexsmobs:caiman_egg', ['Obtained by breeding Caimans with Raw Catfish. Stacks up to 4 times. Baby Caimans will imprint on the nearest entity.']),
  e.addItem('alexsmobs:crocodile_egg', ['Obtained by breeding Crocodiles with Rotten Flesh. Stacks up to 4 times. Baby Crocodiles will imprint on the nearest entity.']),
  e.addItem('alexsmobs:triops_eggs', ['Obtained by breeding Triops with Carrots.']),

//Berry Good
  e.addItem('berry_good:music_disc_fox', ['Sometimes found in the mouths of Foxes.']),
  e.addItem('minecraft:sweet_berries', ['Convert to Sweet Berry Pips to plant.']),
  e.addItem('minecraft:glow_berries', ['Convert to Glow Berry Pips to plant. Can be placed onto Silver Lattices.']),

//Biome Makeover
  e.addItem('biomemakeover:poltergeist', ['Randomly triggers Redstone interactive blocks up to 2 blocks away.']),
  e.addItem('biomemakeover:peat', ['Increases how fast crops grow. Can be dried to create a very potent fuel source.']),
  e.addItem('biomemakeover:peat_farmland', ['Increases how fast crops grow.']),
  e.addItem('biomemakeover:dried_peat', ['Very potent fuel source.']),
  e.addItem('biomemakeover:lightning_bug_bottle', ['Obtained by using an Empty Bottle on a Lightning Bug.']),
  e.addItem('biomemakeover:altar', ['Increases a random Enchant by 1 level, regardless of if it is at the capped or not, but Curses the item enhanced. Powered by Illunite Shards.']),
  e.addItem('biomemakeover:cladded_stone', ['Can be used to create Stone Golems, similar to Iron Golems.']),
  e.addItem('biomemakeover:witch_hat', ['When worn, allows one to haggle with Witches.']),
  e.addItem('biomemakeover:lightning_bottle', ['When thrown, provides the same effects as if a mob had been struck by Lightning. Obtained by using a Bottle O Enchanting on a lightning bug.']),
  e.addItem('biomemakeover:soul_embers', ['Obtained through Witch Haggling. Can be used in place of Blaze Powder.']),
  e.addItem('biomemakeover:stunt_powder', ['Prevents baby mobs from growing up.']),
  e.addItem('biomemakeover:enchanted_totem', ['When activated, instantly grants 1/2 your max HP, 25 seconds of Regeneration II, 60 seconds of Absorption IV, 100 seconds of Fire Resistance I and Resistance I. Removes all Negative Effects.']),
  e.addItem('biomemakeover:cladded_boots', ['Allows for walking on Powdered Snow.']),

//Domestication Innovation
  e.addItem('domesticationinnovation:pet_bed_white', ['Lets tamed mobs respawn. Let them sit on it until ZZZ particles appear, which indicate that its respawn point was set. Mobs respawn at dawn and enchantments are preserved. Workplace for Animal Tamer Villager.']),
  e.addItem('domesticationinnovation:pet_bed_orange', ['Lets tamed mobs respawn. Let them sit on it until ZZZ particles appear, which indicate that its respawn point was set. Mobs respawn at dawn and enchantments are preserved. Workplace for Animal Tamer Villager.']),
  e.addItem('domesticationinnovation:pet_bed_magenta', ['Lets tamed mobs respawn. Let them sit on it until ZZZ particles appear, which indicate that its respawn point was set. Mobs respawn at dawn and enchantments are preserved. Workplace for Animal Tamer Villager.']),
  e.addItem('domesticationinnovation:pet_bed_light_blue', ['Lets tamed mobs respawn. Let them sit on it until ZZZ particles appear, which indicate that its respawn point was set. Mobs respawn at dawn and enchantments are preserved. Workplace for Animal Tamer Villager.']),
  e.addItem('domesticationinnovation:pet_bed_yellow', ['Lets tamed mobs respawn. Let them sit on it until ZZZ particles appear, which indicate that its respawn point was set. Mobs respawn at dawn and enchantments are preserved. Workplace for Animal Tamer Villager.']),
  e.addItem('domesticationinnovation:pet_bed_lime', ['Lets tamed mobs respawn. Let them sit on it until ZZZ particles appear, which indicate that its respawn point was set. Mobs respawn at dawn and enchantments are preserved. Workplace for Animal Tamer Villager.']),
  e.addItem('domesticationinnovation:pet_bed_pink', ['Lets tamed mobs respawn. Let them sit on it until ZZZ particles appear, which indicate that its respawn point was set. Mobs respawn at dawn and enchantments are preserved. Workplace for Animal Tamer Villager.']),
  e.addItem('domesticationinnovation:pet_bed_gray', ['Lets tamed mobs respawn. Let them sit on it until ZZZ particles appear, which indicate that its respawn point was set. Mobs respawn at dawn and enchantments are preserved. Workplace for Animal Tamer Villager.']),
  e.addItem('domesticationinnovation:pet_bed_light_gray', ['Lets tamed mobs respawn. Let them sit on it until ZZZ particles appear, which indicate that its respawn point was set. Mobs respawn at dawn and enchantments are preserved. Workplace for Animal Tamer Villager.']),
  e.addItem('domesticationinnovation:pet_bed_cyan', ['Lets tamed mobs respawn. Let them sit on it until ZZZ particles appear, which indicate that its respawn point was set. Mobs respawn at dawn and enchantments are preserved. Workplace for Animal Tamer Villager.']),
  e.addItem('domesticationinnovation:pet_bed_purple', ['Lets tamed mobs respawn. Let them sit on it until ZZZ particles appear, which indicate that its respawn point was set. Mobs respawn at dawn and enchantments are preserved. Workplace for Animal Tamer Villager.']),
  e.addItem('domesticationinnovation:pet_bed_blue', ['Lets tamed mobs respawn. Let them sit on it until ZZZ particles appear, which indicate that its respawn point was set. Mobs respawn at dawn and enchantments are preserved. Workplace for Animal Tamer Villager.']),
  e.addItem('domesticationinnovation:pet_bed_brown', ['Lets tamed mobs respawn. Let them sit on it until ZZZ particles appear, which indicate that its respawn point was set. Mobs respawn at dawn and enchantments are preserved. Workplace for Animal Tamer Villager.']),
  e.addItem('domesticationinnovation:pet_bed_green', ['Lets tamed mobs respawn. Let them sit on it until ZZZ particles appear, which indicate that its respawn point was set. Mobs respawn at dawn and enchantments are preserved. Workplace for Animal Tamer Villager.']),
  e.addItem('domesticationinnovation:pet_bed_red', ['Lets tamed mobs respawn. Let them sit on it until ZZZ particles appear, which indicate that its respawn point was set. Mobs respawn at dawn and enchantments are preserved. Workplace for Animal Tamer Villager.']),
  e.addItem('domesticationinnovation:pet_bed_black', ['Lets tamed mobs respawn. Let them sit on it until ZZZ particles appear, which indicate that its respawn point was set. Mobs respawn at dawn and enchantments are preserved. Workplace for Animal Tamer Villager.']),
  e.addItem('domesticationinnovation:collar_tag', ['Enchantable. Rename in an Anvil, place onto a pet by interacting with it, and get Collars back by swapping it with any other collar. View a pets enchants by sneaking and looking at them.']),
  e.addItem('domesticationinnovation:feather_on_a_stick', ['When thrown, the closest pet will try to move to its feather to play with it. Useful for moving a pet onto its bed to set its respawn point.']),
  e.addItem('domesticationinnovation:rotten_apple', ['Chance to form if an apple despawns on the ground. Feed to a tamed and saddled Horse to convert to a Zombie Horse.']),
  e.addItem('domesticationinnovation:sinister_carrot', ['Rarely found as loot in Woodland Mansions. Fed to Zombie Horses to turn into a Skeleton Horse. Can be fed to a tamed Rabbit to transorm it into a Killer Rabbit.']),
  e.addItem('domesticationinnovation:deed_of_ownership', ['Purchased from the Animal Tamer Villager. Right Click on a pet you own to bind it to the Deed. If given to another player and they use it on the bound animal, the ownership passes to them.']),
  e.addItem('domesticationinnovation:drum', ['Command groups of pets by interacting to change command modes. Automate by giving a redstone signal.']),
  e.addItem('domesticationinnovation:wayward_lantern', ['If pets are lost in their "follow" mode, they will eventually find their way to the closest Wayward Lantern to you.']),

//Friends and Foes
  e.addItem('friendsandfoes:wildfire_crown', ['Grants 8 seconds of Fire Resistance (starts ticking down upon being on fire).']),
  e.addItem('friendsandfoes:totem_of_freezing', ['Upon reaching half-health, removes all status effects, slows nearby mobs and grants Speed II.']),
  e.addItem('friendsandfoes:totem_of_illusion', ['Upon reaching 1/3 health, removes all status effects, summons Illusions and grants Invisibility.']),
  e.addItem('friendsandfoes:copper_golem_spawn_egg', ['Created by placing a Lightning Rod on a Carved Pumpkin on top of a Copper Block. Randomly presses Copper Buttons and oxidizes over time unless Waxed.']),
  e.addItem('friendsandfoes:tuff_golem_spawn_egg', ['Created by placing a Carved Pumpkin on top of Wool on top of a Tuff Block. Can hold items. Doesnt move if Waxed.']),
  e.addItem('friendsandfoes:glare_spawn_egg', ['Tame with Glow Berries. Flies to dark spots where monsters can spawn and shakes. Breed with Glow Berries.']),
  e.addItem('friendsandfoes:mauler_spawn_egg', ['Feed by Right Clicking with an Enchanted item or book. Stores Exp. Recover by Right Clicking with an empty Glass Bottle. Drops all stored Exp on death.']),

//Galosphere
    e.addItem('galosphere:sterling_helmet', ['Can be equipped with a Banner.']),
    e.addItem('galosphere:sterling_chestplate', ['Can be equipped with a Banner.']),
    e.addItem('galosphere:sterling_leggings', ['Can be equipped with a Banner.']),
    e.addItem('galosphere:sterling_boots', ['Can be equipped with a Banner.']),
    e.addItem('galosphere:sterling_horse_armor', ['Can be equipped with a Banner.']),
    e.addItem('galosphere:silver_bomb', ['Modify Silver Bombs with a Combustion Table. String increases fuse time, Slime increases bounciness, and Gunpowder increases explosive power.']),
    e.addItem('galosphere:combustion_table', ['Modify Silver Bombs with a Combustion Table. String increases fuse time, Slime increases bounciness, and Gunpowder increases explosive power.']),
    e.addItem('galosphere:silver_balance', ['Emits a differing amount of Redstone Signal based on the block placed on top.']),
    e.addItem('galosphere:silver_lattice', ['Silver Lattices can have Glowberries placed onto them.']),
    e.addItem('galosphere:glow_flare', ['Launch with Right Click to cover an area with Glow Ink Clumps which emit light. Emits more light underwater.']),
    e.addItem('galosphere:glow_ink_clumps', ['Launch with Right Click to cover an area with Glow Ink Clumps which emit light. Emits more light underwater.']),
    e.addItem('galosphere:lichen_moss', ['Emits light when stepped on.']),
    e.addItem('galosphere:spectre_flare', ['Grants temporary vision from where it lands.']),
    e.addItem('galosphere:bottle_of_spectre', ['Right Click a Spectre with a Allurite Shard, then a Spyglass to bind the Spyglass to the Spectre. Breed with Lichen Shelfs to create Specterpillars, which burrow into Lichen to form Cordyceps.']),
    e.addItem('galosphere:spectre_spawn_egg', ['Right Click a Spectre with a Allurite Shard, then a Spyglass to bind the Spyglass to the Spectre. Breed with Lichen Shelfs to create Specterpillars, which burrow into Lichen to form Cordyceps.']),
    e.addItem('galosphere:specterpillar_spawn_egg', ['Right Click a Spectre with a Allurite Shard, then a Spyglass to bind the Spyglass to the Spectre. Breed with Lichen Shelfs to create Specterpillars, which burrow into Lichen to form Cordyceps.']),
    e.addItem('galosphere:allurite_shard', ['Right Click a Spectre with a Allurite Shard, then a Spyglass to bind the Spyglass to the Spectre. Breed with Lichen Shelfs to create Specterpillars, which burrow into Lichen to form Cordyceps.']),
    e.addItem('galosphere:lichen_shelf', ['Right Click a Spectre with a Allurite Shard, then a Spyglass to bind the Spyglass to the Spectre. Breed with Lichen Shelfs to create Specterpillars, which burrow into Lichen to form Cordyceps.']),
    e.addItem('galosphere:lichen_cordyceps', ['Restores some Oxygen when eaten underwater. Golden Cordyceps restore more.']),
    e.addItem('galosphere:golden_lichen_cordyceps', ['Restores some Oxygen when eaten underwater. Golden Cordyceps restore more.']),
    e.addItem('galosphere:allurite_block', ['Warped Anchors will redirect nearby Ender Pearl teleportation to itself while negating any damage. Uses up to 4x Allurite blocks as fuel.']),
    e.addItem('galosphere:warped_anchor', ['Warped Anchors will redirect nearby Ender Pearl teleportation to itself while negate any damage. Uses up to 4x Allurite blocks as fuel.']),
    e.addItem('galosphere:lumiere_block', ['Charge Lumiere Blocks with Lightning. Converts some blocks to others. Granite -> Red sand -> Sand. Cobblestone -> Gravel.']),
    e.addItem('galosphere:charged_lumiere_block', ['Charge Lumiere Blocks with Lightning. Converts some blocks to others. Granite -> Red sand -> Sand. Cobblestone -> Gravel.']),
    e.addItem('galosphere:lumiere_shard', ['Use a Lumiere Shard on a Composter to make Glowstone Dust instead of Bonemeal.']),
    e.addItem('minecraft:glowstone_dust', ['Use a Lumiere Shard on a Composter to make Glowstone Dust instead of Bonemeal.']),
    e.addItem('galosphere:monstrometer', ['Charge with Lumiere Blocks. Activate with Right Click to reveal any nearby monsters in a 16 block radius (including under ground).']),
    e.addItem('galosphere:sparkle_spawn_egg', ['Right Click a Sparkle with a pickaxe to harvest their shards. Silk Touch pickaxes grant clusters instead. Feed Glow Lichen to increase the speed at which they regrow their crystals, and breed by feeding Sparkles with crystals Glow Lichen. Sparkles makes nearby Allurite, Amethyst, and Lumiere Clusters sparkle and emit particles.']),
    e.addItem('minecraft:amethyst_cluster', ['Right Click a Sparkle with a pickaxe to harvest their shards. Silk Touch pickaxes grant clusters instead. Feed Glow Lichen to increase the speed at which they regrow their crystals, and breed by feeding Sparkles with crystals Glow Lichen. Sparkles makes nearby Allurite, Amethyst, and Lumiere Clusters sparkle and emit particles.']),
    e.addItem('galosphere:glinted_amethyst_cluster', ['Right Click a Sparkle with a pickaxe to harvest their shards. Silk Touch pickaxes grant clusters instead. Feed Glow Lichen to increase the speed at which they regrow their crystals, and breed by feeding Sparkles with crystals Glow Lichen. Sparkles makes nearby Allurite, Amethyst, and Lumiere Clusters sparkle and emit particles.']),
    e.addItem('galosphere:allurite_cluster', ['Right Click a Sparkle with a pickaxe to harvest their shards. Silk Touch pickaxes grant clusters instead. Feed Glow Lichen to increase the speed at which they regrow their crystals, and breed by feeding Sparkles with crystals Glow Lichen. Sparkles makes nearby Allurite, Amethyst, and Lumiere Clusters sparkle and emit particles.']),
    e.addItem('galosphere:glinted_allurite_cluster', ['Right Click a Sparkle with a pickaxe to harvest their shards. Silk Touch pickaxes grant clusters instead. Feed Glow Lichen to increase the speed at which they regrow their crystals, and breed by feeding Sparkles with crystals Glow Lichen. Sparkles makes nearby Allurite, Amethyst, and Lumiere Clusters sparkle and emit particles.']),
    e.addItem('galosphere:lumiere_cluster', ['Right Click a Sparkle with a pickaxe to harvest their shards. Silk Touch pickaxes grant clusters instead. Feed Glow Lichen to increase the speed at which they regrow their crystals, and breed by feeding Sparkles with crystals Glow Lichen. Sparkles makes nearby Allurite, Amethyst, and Lumiere Clusters sparkle and emit particles.']),
    e.addItem('galosphere:glinted_lumiere_cluster', ['Right Click a Sparkle with a pickaxe to harvest their shards. Silk Touch pickaxes grant clusters instead. Feed Glow Lichen to increase the speed at which they regrow their crystals, and breed by feeding Sparkles with crystals Glow Lichen. Sparkles makes nearby Allurite, Amethyst, and Lumiere Clusters sparkle and emit particles.']),
    e.addItem('galosphere:pink_salt', ['When placed under a Soul Campfire, Pink Salt converts to Rose Pink Salt which converts to Pastel Pink Salt.']),
    e.addItem('galosphere:rose_pink_salt', ['When placed under a Soul Campfire, Pink Salt converts to Rose Pink Salt which converts to Pastel Pink Salt.']),
    e.addItem('galosphere:pastel_pink_salt', ['When placed under a Soul Campfire, Pink Salt converts to Rose Pink Salt which converts to Pastel Pink Salt.']),
    e.addItem('galosphere:pink_salt_straw', ['Converts contents of a Composter underneath it to Coarse Dirt.']),
    e.addItem('minecraft:coarse_dirt', ['Converts contents of a Composter underneath it to Coarse Dirt.']),
    e.addItem('galosphere:shadow_frame', ['Place blocks into the frame. Allows one to pass through the framed blocks as if they were air.']),
    e.addItem('galosphere:stranded_membrane_block', ['Moves items and entities from the starting point to the end point.']),
    e.addItem('galosphere:preserved_flesh', ['Can be eaten up to 180 times.']),
    e.addItem('galosphere:saltbound_tablet', ['Charge to summon salt pillars in the direction you are facing. If used when looking down, summons salt pillars around you.']),
    e.addItem('galosphere:pink_salt_chamber', ['Place a Pink Salt Cluster on top to cause the Pink Salt Chamber to summon Preserved.']),
    e.addItem('galosphere:pink_salt_cluster', ['Place a Pink Salt Cluster on top to cause the Pink Salt Chamber to summon Preserved.']),


//Hellion's Sniffer Plus
  e.addItem('minecraft:torchflower', ['Emits light.']),
  e.addItem('minecraft:sniffer_egg', ['Can be given a Chest. Can be saddled and ridden. Give an Ominous Banner to  cause to head towards a Pillager Outpost.']),

//Incubation
  e.addItem('incubation:twig_nest', ['Chickens will try to pathfind to this block to lay eggs within it. Eggs can be removed through Hoppers.']),
  e.addItem('incubation:hay_nest', ['Chickens will try to pathfind to this block to lay eggs within it. Eggs can be removed through Hoppers.']),

//Jaden's Nether Expansion
  e.addItem('netherexp:souled_geyser', ['Launches entities up when stepped on.']),
  e.addItem('netherexp:basaltic_geyser', ['Launches entities up when stepped on.']),
  e.addItem('netherexp:crimson_sporeshroom', ['Negates fall damage and is bouncy. Spreads when bonemealed.']),
  e.addItem('netherexp:warped_sporeshroom', ['Negates fall damage and is bouncy. Spreads when bonemealed.']),
  e.addItem('netherexp:lightspores', ['Use on their respective wart block to make them spotted.']),
  e.addItem('netherexp:nightspores', ['Use on their respective wart block to make them spotted.']),
  e.addItem('minecraft:crimson_nylium', ['Use a shovel on the respective block to form a path block.']),
  e.addItem('minecraft:warped_nylium', ['Use a shovel on the respective block to form a path block.']),
  e.addItem('minecraft:soul_sand', ['Use a shovel on the respective block to form a path block.']),
  e.addItem('netherexp:soul_path', ['Use a shovel on the respective block to form a path block.']),
  e.addItem('netherexp:warped_nylium_path', ['Use a shovel on the respective block to form a path block.']),
  e.addItem('netherexp:crimson_nylium_path', ['Use a shovel on the respective block to form a path block.']),
  e.addItem('netherexp:soul_swirls', ['Temporarily grants immunity to the slowness of soul sand when stepped on.']),
  e.addItem('netherexp:chiseled_soul_slate_bricks', ['Can be ignited with Flint and Steel.']),
  e.addItem('netherexp:etched_soul_slate_bricks', ['Can be ignited with Flint and Steel.']),
  e.addItem('netherexp:chiseled_soul_slate_tiles', ['Can be ignited with Flint and Steel.']),
  e.addItem('netherexp:etched_soul_slate_tiles', ['Can be ignited with Flint and Steel.']),
  e.addItem('netherexp:soul_magma_block', ['Damages you if sprinted on without Soul Speed.']),
  e.addItem('netherexp:fossil_ore', ['Fossil Ore is formed when a Skeleton dies on Soul Sand. Overtime, becomes Fossil Fuel Ore.']),
  e.addItem('netherexp:fossil_fuel_ore', ['Fossil Ore is formed when a Skeleton dies on Soul Sand. Overtime, becomes Fossil Fuel Ore.']),
  e.addItem('netherexp:fossil_fuel', ['Fossil Ore is formed when a Skeleton dies on Soul Sand. Overtime, becomes Fossil Fuel Ore. Fossil Fuel acts as an alternative for Coal.']),
  e.addItem('netherexp:ectoplasm_bucket', ['Forms Black Ice when it comes in contact with Water.']),
  e.addItem('netherexp:black_ice', ['Formed when Ectoplasm comes in contact with Water. Converts surrounding Soul Sand to Pale Soul Slate.']),
  e.addItem('netherexp:bone_cortical', ['Can have Leather placed on it.']),
  e.addItem('netherexp:stridite', ['Found by brushing Suspicious Soul Sand.']),
  e.addItem('netherexp:treacherous_flame', ['Treacherous Flames can be obtained by completing Treacherous Candles. Use them to unlock Brazier Chests or grind into experience with the Sculk Grinder.']),
  e.addItem('netherexp:treacherous_candle', ['Treacherous Flames can be obtained by completing Treacherous Candles. Use them to unlock Brazier Chests or grind into experience with the Sculk Grinder.']),
  e.addItem('netherexp:brazier_chest', ['Treacherous Flames can be obtained by completing Treacherous Candles. Use them to unlock Brazier Chests or grind into experience with the Sculk Grinder.']),
  e.addItem('netherexp:sculk_grinder', ['Treacherous Flames can be obtained by completing Treacherous Candles. Use them to unlock Brazier Chests or grind into experience with the Sculk Grinder.']),
  e.addItem('netherexp:shotgun_fist', ['Shotgun-Fists are fueled with Wraithing Flesh.']),
  e.addItem('netherexp:wraithing_flesh', ['Shotgun-Fists are fueled with Wraithing Flesh.']),
  e.addItem('netherexp:pump_charge_shotgun', ['Shotgun-Fists are fueled with Wraithing Flesh. Can be pumped up to four times, but may explode if overly pumped.']),
  e.addItem('netherexp:will_o_wisp', ['Tracks the target it is thrown at.']),
  e.addItem('netherexp:phasmo_arrow', ['Shoots through blocks and can hit Apparitions and Wisps.']),
  e.addItem('netherexp:soul_glass', ['Can be walked through.']),
  e.addItem('netherexp:ochre_frogmist', ['Obtained when Frogs eat Ecto Slabs. Can be stacked multiple times.']),
  e.addItem('netherexp:verdant_frogmist', ['Obtained when Frogs eat Ecto Slabs. Can be stacked multiple times.']),
  e.addItem('netherexp:pearlescent_frogmist', ['Obtained when Frogs eat Ecto Slabs. Can be stacked multiple times.']),
  e.addItem('netherexp:sorrowsquash', ['Obtained by Pumpkin Seeds planted on Soul Sand.']),
  e.addItem('netherexp:netherite_plated_block', ['Obtained when their respective Netherite block touches Ectoplasm.']),
  e.addItem('netherexp:netherite_grate', ['Obtained when their respective Netherite block touches Ectoplasm.']),
  e.addItem('netherexp:cut_netherite_block', ['Obtained when their respective Netherite block touches Ectoplasm.']),
  e.addItem('netherexp:cut_netherite_stairs', ['Obtained when their respective Netherite block touches Ectoplasm.']),
  e.addItem('netherexp:cut_netherite_slab', ['Obtained when their respective Netherite block touches Ectoplasm.']),
  e.addItem('netherexp:cut_netherite_pillar', ['Obtained when their respective Netherite block touches Ectoplasm.']),
  e.addItem('netherexp:rusty_netherite_plated_block', ['Obtained when their respective Netherite block touches Ectoplasm.']),
  e.addItem('netherexp:rusty_netherite_grate', ['Obtained when their respective Netherite block touches Ectoplasm.']),
  e.addItem('netherexp:rusty_cut_netherite_block', ['Obtained when their respective Netherite block touches Ectoplasm.']),
  e.addItem('netherexp:rusty_cut_netherite_stairs', ['Obtained when their respective Netherite block touches Ectoplasm.']),
  e.addItem('netherexp:rusty_cut_netherite_slab', ['Obtained when their respective Netherite block touches Ectoplasm.']),
  e.addItem('netherexp:rusty_cut_netherite_pillar', ['Obtained when their respective Netherite block touches Ectoplasm.']),
  e.addItem('netherexp:inscribed_panel', ['Right-click to cycle through the different symbols.']),
  e.addItem('netherexp:ossified_gargoyle_statue', ['Can be interacted with by Apparitions to create their respective mob.']),
  e.addItem('netherexp:trample_gargoyle_statue', ['Can be interacted with by Apparitions to create their respective mob.']),
  e.addItem('netherexp:phase_gargoyle_statue', ['Can be interacted with by Apparitions to create their respective mob.']),
  e.addItem('netherexp:ghoul_gargoyle_statue', ['Can be interacted with by Apparitions to create their respective mob.']),
  e.addItem('netherexp:wretched_gargoyle_statue', ['Can be interacted with by Apparitions to create their respective mob.']),
  e.addItem('netherexp:treacherous_gargoyle_statue', ['Can be interacted with by Apparitions to create their respective mob.']),
  e.addItem('netherexp:cirripedia_gargoyle_statue', ['Can be interacted with by Apparitions to create their respective mob.']),
  e.addItem('netherexp:occult_gargoyle_statue', ['Can be interacted with by Apparitions to create their respective mob.']),
  e.addItem('netherexp:sealed_gargoyle_statue', ['Can be interacted with by Apparitions to create their respective mob.']),
  e.addItem('netherexp:obfuscated_gargoyle_statue', ['Can be interacted with by Apparitions to create their respective mob.']),
  e.addItem('netherexp:antidote', ['Gives immunity to the effect for a period of time. Made by using Warped Wart instead of Nether Wart.']),
  e.addItem('netherexp:grenade_antidote', ['Gives immunity to the effect for a period of time. Made by using Warped Wart instead of Nether Wart.']),

//Supplementaries
  e.addItem('supplementaries:slingshot', ['Shoots blocks which are placed where they land if their position is suitable, pulls from the left side of the hotbar first. Enchantable.']),
  e.addItem('supplementaries:quiver', ['Dropped by Skeletons. Access with "`".']),
  e.addItem('supplementaries:slice_map', ['Displays the world from a certain Y-level.']),
  e.addItem('supplementaries:flute', ['Play to summon nearby non-sitting pets to the player. Can be bound to a specific pet by clicking it to the pet.']),
  e.addItem('supplementaries:wrench', ['Rotates any rotatable block. Shift right click to reverse the rotation direction.']),
  e.addItem('supplementaries:soap', ['Undyes items. Cleans away oxidation levels by one when used on Copper. Cleans pets and sheep. Washes Blackboards, Antique Globes, Maps, Sticky Pistones, and Tipped Spikes.']),
  e.addItem('supplementaries:bubble_blower', ['Fun novelty item. If enchanted with Stasis, places soap bubble blocks mid air wherever you aim. Can be replaced with normal blocks.']),
  e.addItem('supplementaries:antique_ink', ['Can be used on Signs, Maps, Map Atlas, Globes, Written Books.']),
  e.addItem('supplementaries:key', ['Locks Safes, Netherite Doors, Netherite Trapdoors, and Lock Blocks. Rename to desired password.']),
  e.addItem('supplementaries:pancake', ['Accepts Honey, Chocolate, and Syrup as toppings. Can be inserted into a Jukebox.']),

//Storage Drawers
e.addItem('storagedrawers:controller', ['Deposit items here to insert into corresponding storage drawers that are connected.']),

//Upgrade Aquatic
  e.addItem('upgrade_aquatic:tooth_door', ['Closes after opening.']),
  e.addItem('upgrade_aquatic:tooth_trapdoor', ['Closes after opening.']),
  e.addItem('upgrade_aquatic:coralstone', ['Infuse by placing next to coral. Give Redstone to grow more coral.']),
  e.addItem('upgrade_aquatic:tube_coralstone', ['Give Redstone to grow more coral.']),
  e.addItem('upgrade_aquatic:brain_coralstone', ['Give Redstone to grow more coral.']),
  e.addItem('upgrade_aquatic:bubble_coralstone', ['Give Redstone to grow more coral.']),
  e.addItem('upgrade_aquatic:fire_coralstone', ['Give Redstone to grow more coral.']),
  e.addItem('upgrade_aquatic:horn_coralstone', ['Give Redstone to grow more coral.']),
  e.addItem('upgrade_aquatic:acan_coralstone', ['Give Redstone to grow more coral.']),
  e.addItem('upgrade_aquatic:finger_coralstone', ['Give Redstone to grow more coral.']),
  e.addItem('upgrade_aquatic:star_coralstone', ['Give Redstone to grow more coral.']),
  e.addItem('upgrade_aquatic:moss_coralstone', ['Give Redstone to grow more coral.']),
  e.addItem('upgrade_aquatic:petal_coralstone', ['Give Redstone to grow more coral.']),
  e.addItem('upgrade_aquatic:branch_coralstone', ['Give Redstone to grow more coral.']),
  e.addItem('upgrade_aquatic:rock_coralstone', ['Give Redstone to grow more coral.']),
  e.addItem('upgrade_aquatic:pillow_coralstone', ['Give Redstone to grow more coral.']),
  e.addItem('upgrade_aquatic:silk_coralstone', ['Give Redstone to grow more coral.']),
  e.addItem('upgrade_aquatic:chrome_coralstone', ['Give Redstone to grow more coral.']),
  e.addItem('upgrade_aquatic:prismarine_coralstone', ['Give Redstone to grow more coral.']),
  e.addItem('upgrade_aquatic:bedroll', ['Lets you sleep without setting your spawn.']),
  e.addItem('upgrade_aquatic:white_bedroll', ['Lets you sleep without setting your spawn.']),
  e.addItem('upgrade_aquatic:light_gray_bedroll', ['Lets you sleep without setting your spawn.']),
  e.addItem('upgrade_aquatic:gray_bedroll', ['Lets you sleep without setting your spawn.']),
  e.addItem('upgrade_aquatic:black_bedroll', ['Lets you sleep without setting your spawn.']),
  e.addItem('upgrade_aquatic:brown_bedroll', ['Lets you sleep without setting your spawn.']),
  e.addItem('upgrade_aquatic:red_bedroll', ['Lets you sleep without setting your spawn.']),
  e.addItem('upgrade_aquatic:orange_bedroll', ['Lets you sleep without setting your spawn.']),
  e.addItem('upgrade_aquatic:yellow_bedroll', ['Lets you sleep without setting your spawn.']),
  e.addItem('upgrade_aquatic:lime_bedroll', ['Lets you sleep without setting your spawn.']),
  e.addItem('upgrade_aquatic:green_bedroll', ['Lets you sleep without setting your spawn.']),
  e.addItem('upgrade_aquatic:cyan_bedroll', ['Lets you sleep without setting your spawn.']),
  e.addItem('upgrade_aquatic:light_blue_bedroll', ['Lets you sleep without setting your spawn.']),
  e.addItem('upgrade_aquatic:blue_bedroll', ['Lets you sleep without setting your spawn.']),
  e.addItem('upgrade_aquatic:purple_bedroll', ['Lets you sleep without setting your spawn.']),
  e.addItem('upgrade_aquatic:magenta_bedroll', ['Lets you sleep without setting your spawn.']),
  e.addItem('upgrade_aquatic:pink_bedroll', ['Lets you sleep without setting your spawn.']),
  e.addItem('upgrade_aquatic:pickerelweed_block', ['Half-block, but slows movement through it.']),
  e.addItem('upgrade_aquatic:boiled_pickerelweed_block', ['Half-block.']),
  e.addItem('upgrade_aquatic:elder_eye', ['Right-click to activate. Emits a redstone signal when detects an entity in line of sight.']),
  e.addItem('upgrade_aquatic:pike_spawn_egg', ['Hunts other fish. Has 16 different biome dependent variants.']),
  e.addItem('upgrade_aquatic:mulberry', ['Plantable on the underside of River Leaves']),
  e.addItem('minecraft:glow_ink_sac', ['Revives dead coral.']),

//Simply Swords
  e.addItem('simplyswords:runefused_gem', ['Right click onto a unique weapon to socket.']),
  e.addItem('simplyswords:netherfused_gem', ['Right click onto a unique weapon to socket.']),
  e.addItem('simplyswords:empowered_remnant', ['A concentrated power melted down from a unique weapon.']),
  e.addItem('simplyswords:brimstone_claymore', ['Discover the crafting recipe for this unique weapon by exploring structures.']),
  e.addItem('simplyswords:watcher_claymore', ['Discover the crafting recipe for this unique weapon by exploring structures.']),
  e.addItem('simplyswords:storms_edge', ['Discover the crafting recipe for this unique weapon by exploring structures.']),
  e.addItem('simplyswords:stormbringer', ['Discover the crafting recipe for this unique weapon by exploring structures.']),
  e.addItem('simplyswords:bramblethorn', ['Discover the crafting recipe for this unique weapon by exploring structures.']),
  e.addItem('simplyswords:watching_warglaive', ['Discover the crafting recipe for this unique weapon by exploring structures.']),
  e.addItem('simplyswords:toxic_longsword', ['Discover the crafting recipe for this unique weapon by exploring structures.']),
  e.addItem('simplyswords:emberblade', ['Discover the crafting recipe for this unique weapon by exploring structures.']),
  e.addItem('simplyswords:hearthflame', ['Discover the crafting recipe for this unique weapon by exploring structures.']),
  e.addItem('simplyswords:soulkeeper', ['Discover the crafting recipe for this unique weapon by exploring structures.']),
  e.addItem('simplyswords:twisted_blade', ['Discover the crafting recipe for this unique weapon by exploring structures.']),
  e.addItem('simplyswords:soulstealer', ['Discover the crafting recipe for this unique weapon by exploring structures.']),
  e.addItem('simplyswords:soulrender', ['Discover the crafting recipe for this unique weapon by exploring structures.']),
  e.addItem('simplyswords:soulpyre', ['Discover the crafting recipe for this unique weapon by exploring structures.']),
  e.addItem('simplyswords:frostfall', ['Discover the crafting recipe for this unique weapon by exploring structures.']),
  e.addItem('simplyswords:molten_edge', ['Discover the crafting recipe for this unique weapon by exploring structures.']),
  e.addItem('simplyswords:livyatan', ['Discover the crafting recipe for this unique weapon by exploring structures.']),
  e.addItem('simplyswords:icewhisper', ['Discover the crafting recipe for this unique weapon by exploring structures.']),
  e.addItem('simplyswords:arcanethyst', ['Discover the crafting recipe for this unique weapon by exploring structures.']),
  e.addItem('simplyswords:thunderbrand', ['Discover the crafting recipe for this unique weapon by exploring structures.']),
  e.addItem('simplyswords:mjolnir', ['Discover the crafting recipe for this unique weapon by exploring structures.']),
  e.addItem('simplyswords:slumbering_lichblade', ['It is rumored the mighty Dread Queen carries this blade..']),
  e.addItem('simplyswords:shadowsting', ['Discover the crafting recipe for this unique weapon by exploring structures.']),
  e.addItem('simplyswords:whisperwind', ['Discover the crafting recipe for this unique weapon by exploring structures.']),
  e.addItem('simplyswords:emberlash', ['Discover the crafting recipe for this unique weapon by exploring structures.']),
  e.addItem('simplyswords:waxweaver', ['Discover the crafting recipe for this unique weapon by exploring structures.']),
  e.addItem('simplyswords:hiveheart', ['Discover the crafting recipe for this unique weapon by exploring structures.']),
  e.addItem('simplyswords:stars_edge', ['Discover the crafting recipe for this unique weapon by exploring structures.']),
  e.addItem('simplyswords:wickpiercer', ['Discover the crafting recipe for this unique weapon by exploring structures.']),
  e.addItem('simplyswords:tempest', ['Discover the crafting recipe for this unique weapon by exploring structures.']),
  e.addItem('simplyswords:flamewind', ['Discover the crafting recipe for this unique weapon by exploring structures.']),
  e.addItem('simplyswords:ribboncleaver', ['Discover the crafting recipe for this unique weapon by exploring structures.']),
  e.addItem('simplyswords:enigma', ['Discover the crafting recipe for this unique weapon by exploring structures.']),
  e.addItem('simplyswords:magiscythe', ['Discover the crafting recipe for this unique weapon by exploring structures.']),
  e.addItem('simplyswords:magispear', ['Discover the crafting recipe for this unique weapon by exploring structures.']),
  e.addItem('simplyswords:magiblade', ['Discover the crafting recipe for this unique weapon by exploring structures.']),
  e.addItem('simplyswords:caelestis', ['Discover the crafting recipe for this unique weapon by exploring structures.']),
  e.addItem('simplyswords:decaying_relic', ['It is rumored to be found in a magical tower.']),

//Wilder Wild
  e.addItem('wilderwild:stone_chest', ['Needs to be clicked multiple times to open.']),
  e.addItem('wilderwild:termite_mound', ['Converts nearby Wood to its Stripped Variant.']),
  e.addItem('wilderwild:ancient_horn', ['Sends a blast that deals massive damage.']),
  e.addItem('wilderwild:prickly_pear', ['May be found on top of cacti.']),
  e.addItem('wilderwild:echo_glass', ['Cracks in the sun, but is resistant to explosions and heals in the dark.']),

  e.addItem('oreganized:silver_mirror', ['Glows bright blue when the undead are nearby.']),
  e.addItem('galosphere:barometer', ['Tells you the weather forecast.'])
})