
[options]
	#Move camera position in x direction
	#Range: > -2147483648
	x = 0
	#Move camera position in y direction
	#Range: > -2147483648
	y = 0
	#Move camera position in z direction
	#Range: > -2147483648
	z = 53
	#Saved camera position in x direction
	#Range: 4.9E-324 ~ 1.7976931348623157E308
	sx = 4.9E-324
	#Saved camera position in y direction
	#Range: 4.9E-324 ~ 1.7976931348623157E308
	sy = 4.9E-324
	#Saved camera position in z direction
	#Range: 4.9E-324 ~ 1.7976931348623157E308
	sz = 83.0
	#Saved camera pitch position 
	#Range: > -2147483648
	pitch = 0
	#Saved camera yaw position
	#Range: > -2147483648
	yaw = 0
	#Stop camera moving
	stop = false

